## @name health
#GET {{domain_dev}}/api/main/health/heartbeat
#Authorization: Bearer {{auth_token}}


# @name sentence-transformer
POST https://127.0.0.1:8080/api/main/msmarco-distilbert-base-tas-b/embedding
Authorization: Bearer <auth_token>
Content-Type: application/json

{
  "input": [
    "Do aliens exist?"
  ],
  "is_preprocessed": false,
  "preprocessing_kwargs": {},
  "model_kwargs": {},
  "task_kwargs": {},
  "adapter_name": ""
}

###
# @name bertviz_worker
POST https://172.17.0.1:443/api/main/bertviz-test/question-answering  
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMT0NBTF9TUVVBUkVfVVNFUiIsImlzcyI6Ii9MT0NBTF9TUVVBUkVfUkVBTE0iLCJleHAiOjk5OTk5OTk5OTl9.ZMIA74nVTfhnQr_BCrVF3yR_xK2ENSGSGVJEj7B9p6n1O7VhikDDLmiJ8hPurlERAdKCaAdmpTU9cjWGu1KKf-7h6mRSvyE4RPSUc3W8VGT8JFuVpOb2eJqI5LRGHBZdz8e75BlmPn11D2SLWAFRgfhV1DbucP0IoiCiuVv8ltvxnKfd3WBxc6i7-wKngFiNUyF5_h1_f7faBAad4ijlcRiycwo71CWe60zDOIfC5jymb4RUPyvUyTn9dQ-soAeLwmBF5SZYmCtHPmpX8aHO0Y37a9VsdyMmxrSVOVS6SzLTgfFFddDqvcgMpD517vuNhlVg2n08bL7Ys2ujD_cX4-IGZALZI9Umj0T4cWI_bwAXxK81zN81JIPOrNxSO0z9INE7ohVMTDX1UzQajEIDLW9WsjhGXBHxRm2sUePGV7C8vYcxg1i2oVo0nb1TUv4W9hdkGvj_S_diSSNM8cY0lQ_8QlrPTnJzYjIQURTIRPFWbAmD3r9LDgH30FZ6L2Ejfh6fJp-q43SnK7xSPPHma8U9ovn4CSL_spMrFKLH-wpMsv2ns4DKtWwPv2V30vIAOruOi2ong4YMsP-W9ajx0fjQQGxXYifZEb5SLI0pILjjI_ulerwI-DEwej_AKYXahIYhBP3AUwauNJ57KrEOiQ939QHp9j2og3mwsvX7LwA
Content-Type: application/json

{
  "input": [
    "Who stars in The Matrix?", "The Matrix is a 1999 science fiction action's film written 'and' directed by The 'Wachowskis', starring Keanu Reeves, Laurence."
  ],
  "is_preprocessed": false,
  "preprocessing_kwargs": {},
  "model_kwargs": {},
  "task_kwargs": {},
  "explain_kwargs": {"method": "bertviz"},
  "adapter_name": "AdapterHub/bert-base-uncased-pf-squad_v2"
}

###
## @name task_output
GET https://172.17.0.1:443/api/main/task_result/55ec4c82-153f-4f30-8c98-a56dd0e63893
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMT0NBTF9TUVVBUkVfVVNFUiIsImlzcyI6Ii9MT0NBTF9TUVVBUkVfUkVBTE0iLCJleHAiOjk5OTk5OTk5OTl9.ZMIA74nVTfhnQr_BCrVF3yR_xK2ENSGSGVJEj7B9p6n1O7VhikDDLmiJ8hPurlERAdKCaAdmpTU9cjWGu1KKf-7h6mRSvyE4RPSUc3W8VGT8JFuVpOb2eJqI5LRGHBZdz8e75BlmPn11D2SLWAFRgfhV1DbucP0IoiCiuVv8ltvxnKfd3WBxc6i7-wKngFiNUyF5_h1_f7faBAad4ijlcRiycwo71CWe60zDOIfC5jymb4RUPyvUyTn9dQ-soAeLwmBF5SZYmCtHPmpX8aHO0Y37a9VsdyMmxrSVOVS6SzLTgfFFddDqvcgMpD517vuNhlVg2n08bL7Ys2ujD_cX4-IGZALZI9Umj0T4cWI_bwAXxK81zN81JIPOrNxSO0z9INE7ohVMTDX1UzQajEIDLW9WsjhGXBHxRm2sUePGV7C8vYcxg1i2oVo0nb1TUv4W9hdkGvj_S_diSSNM8cY0lQ_8QlrPTnJzYjIQURTIRPFWbAmD3r9LDgH30FZ6L2Ejfh6fJp-q43SnK7xSPPHma8U9ovn4CSL_spMrFKLH-wpMsv2ns4DKtWwPv2V30vIAOruOi2ong4YMsP-W9ajx0fjQQGxXYifZEb5SLI0pILjjI_ulerwI-DEwej_AKYXahIYhBP3AUwauNJ57KrEOiQ939QHp9j2og3mwsvX7LwA
Content-Type: application/json